version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: linkedin-scraper
    volumes:
      - ./:/project
    working_dir: /project
    environment:
      - PYTHONPATH=/project
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=linkedin_jobs
    command: ["tail", "-f", "/dev/null"]  # 暫時保持容器運行
    restart: "no"  # 禁用自動重啟
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: linkedin-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=linkedin_jobs
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data: