
version: 2

models:
  - name: mart-orders_detail
    description: "order detail from shopline"
    columns:
      - name: order_number
        description: "order_number"
        tests:
          - not_null
      
      - name: status
        description: "order_number"
      
      - name: customer_id
        description: "customer_id"
      
      - name: customer_name
        description: "customer_name"
      
      - name: created_from
        description: "created_from"

      - name: created_at
        description: "created_at"
      
      - name: product_subscription_period
        description: "product_subscription_period"
      
      - name: subtotal_dollars
        description: "subtotal_dollars"

      - name: order_discount_dollars
        description: "order_discount_dollars"

      - name: user_credit_dollars
        description: "user_credit_dollars"
      
      - name: order_discount_dollars
        description: "order_discount_dollars"

      - name: user_credit_dollars
        description: "user_credit_dollars"
      
      - name: total_dollars
        description: "total_dollars"
      
      - name: order_points_to_cash_dollars
        description: "order_points_to_cash_dollars"
      
      - name: invoice_buyer_name
        description: "invoice_buyer_name"

      - name: agent_name
        description: "agent_name"

      - name: created_by_channel_name
        description: "created_by_channel_name"

      - name: delivery_address_country
        description: "delivery_address_country"

      - name: delivery_address_city
        description: "delivery_address_city"

      - name: delivery_address_state
        description: "delivery_address_state"

      - name: utm_source
        description: "utm_source"

      - name: utm_medium
        description: "utm_medium"

      - name: utm_campaign
        description: "utm_campaign"

      - name: utm_term
        description: "utm_term"

      - name: membership_tier_name
        description: "membership_tier_name"

      - name: item_type
        description: "item_type"
      
      - name: item_id
        description: "item_id"

      - name: item_name
        description: "item_name"
      
      - name: sku
        description: "item_sku"
      
      - name: quantity
        description: "quantity"

      - name: item_price
        description: "item_price"

      - name: total_dollars
        description: "total_dollars"
      
      - name: created_by
        description: "created_by"